package JILBase;

enum TokenType {
    // Types of constants
    CHAR_CONSTANT, DECIMAL_CONSTANT, INT_CONSTANT, STRING_CONSTANT, EOF,

    COMMENT,

    VARIABLE, DATA_TYPE, FUNCTION,

    //Operators
    LESS_THAN, LESS_EQUAL, GREATER_THAN, GREATER_EQUAL, EQUAL, SEMICOLON,
    ASSIGNMENT, ADD, SUB, MUL, DIV, DOT, MOD, INCREMENT, DECREMENT, COMMA, COLON,
    NOT_EQUAL, OR, AND, NOT,
    BITWISE_AND, BITWISE_OR, BITWISE_NOT, BITWISE_XOR, RIGHT_SHIFT, LEFT_SHIFT,
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, NEWLINE,

    // Keywords
    TRUE, FALSE, IF, ELSE, RETURN, WHILE, FOR, CONST,
    BOOL, CHAR, DECIMAL, INT, STRING, VOID,
    CALL, DECLARE, FUNC, IMPORT, INITIAL, NULL, TEMP;
}